### ISSUE TITLE
Cannot find my device

### ISSUE THREAD

**Issue by marci144** [Grovkillen/ESP_Easy_Webdumper#3]
First time for me to try WebDumper, so I believe I'm doing something wrong. I have an 8266 updated to a recent version, but WebDumper is not able to see it..
I run it on Win10.
tks
Marcello
![2018-09-29 15_17_22-settings](https://user-images.githubusercontent.com/24860592/46246284-7875e500-c3fb-11e8-879e-92fe2a1e4279.png)

**Comment by Grovkillen** [comment]
Have you copied the app data zip file to the same folder?

**Comment by marci144** [comment]
yes the ZIP is there... I move there the content of the zip file (just in case I didn't understand) but same result !

**Comment by Grovkillen** [comment]
You haven't checked anything in the list, could you test that?

Do you have a APP_DATA folder?

**Comment by marci144** [comment]
yes  I have the APP_DATA folder ... and unfortunately same result checking everything on the list!
![2018-09-29 19_17_12-giardino](https://user-images.githubusercontent.com/24860592/46248675-b6cfcc00-c41c-11e8-890a-648826d9031d.png)
![2018-09-29 19_18_09-app_data](https://user-images.githubusercontent.com/24860592/46248677-be8f7080-c41c-11e8-8f9e-c576307e3d93.png)

**Comment by Grovkillen** [comment]
Ok, are you running 32- or 64-bit Windows?

**Comment by marci144** [comment]
64 bit

**Comment by marci144** [comment]
PROBLEM SOLVED 

Running the program as Administrator everything works!!

It's a bug, but there is a reasonable work-around.

Best
Marcello

**Comment by Grovkillen** [comment]
Probably only once it's enough. Try to run it as normal after the initial
admin run.

Den ons 10 okt. 2018 18:46marci144 <notifications@github.com> skrev:
