### ISSUE TITLE
Feature Request: Ability to select more then 12 devices to capture

### ISSUE THREAD

**Issue by itProfi** [Grovkillen/ESP_Easy_Webdumper#4]
Thank yoy for this utiluty! Can i dump more then 12 devices?
![28-10-2018 123324](https://user-images.githubusercontent.com/6728198/47614251-c428b680-daad-11e8-833b-4ad26ff82e54.jpg)

**Comment by Grovkillen** [comment]
Not currently but I will make maximum number of devices optional in a soon to be update.

**Comment by itProfi** [comment]
Is it in progress::)?
